### ISSUE TITLE
Race conditions

### ISSUE THREAD

**Issue by matchstick** [dsoprea/go-exif-knife#2]
When running calls to go-exif-knife in parallel in a test with "-race" it warns of data races.
File with details is attached.

To see code check out http://github.com/matchstick/exif-races.

[race.txt](https://github.com/dsoprea/go-exif-knife/files/4883490/race.txt)

**Comment by dsoprea** [comment]
I'll take a look. I'm currently traveling.

**Comment by dsoprea** [comment]
Try it now. I couldn't reproduce the race condition issues (since they're race conditions, it's inherently sensitive to your local environment). Race conditions aren't really an issue for this project since it's a non-concurrent command-line utility. However, I added locking primitives to go-logging (since this poses a risk to other projects).

**Comment by matchstick** [comment]
Thanks, the problem is gone now.
